apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: permissao-sessao
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi