apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-imagens
spec:
  storageClassName: standard
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/volume-imagens"
    type: DirectoryOrCreate